USER_ROLE_ADMIN = 40
USER_ROLE_FAMILY = 20
USER_ROLE_VOLUNTEER = 10
USER_ROLE_ANONYMOUS = 5

USER_STATUS_ACTIVE = 10
USER_STATUS_PENDING = 5
USER_STATUS_BLACKLIST = 3

JWT_SECRET = b'\xf7\xb6k\xabP\xce\xc1\xaf\xad\x86\xcf\x84\x02\x80\xa0\xe0'
